apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-resinv-mongodb
  labels:
    app: {{.Release.Name}}-resinv-mongodb
spec:
  ports:
  - port: {{.Values.mongodb.port}}
    targetPort: resinv-mongodb
    name: tcp-resinv-mongodb
  selector:
    app: {{.Release.Name}}-resinv-mongodb